/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300067965
 */
public class EncryptDecrypt extends javax.swing.JFrame {
    /*
        encAndRet
        
        This method receive a string value, declares the constant integer variables SHFT and MAX and assigns them 3 and 31 respectively, string variable encMessage, declares the char variable tempChar, declares the integer variable tempAcsii, uses a for loop statement, sets tempChar to the i character of the recieved variable, sets tempAcsii to the integer value of tempChar, 
        
        sets tempAcsii to 3 added to itself, sets tempChar to the char value of tempAcsii, sets encMessage to tempChar added to itself, if statement used with the text box EncOut set to encMessage if it is true and else statement used if the if statement parameters are not met with the text box 
    
        displaying a message saying that the inputted value is not acceptable.
    
        Parameters: String
        
        Returns: void
    */
    public void encAndOut(String s1)
    {
        final int SHFT = 3;
        final int MAX = 31;
        String encMessage = "";
        char tempChar;
        int tempAcsii;
        
        for (int i = 0; i < s1.length(); i++)
        {
            tempChar = s1.charAt(i);
            tempAcsii = (int) tempChar;
            tempAcsii = tempAcsii + SHFT;
            tempChar = (char) tempAcsii;
            encMessage = encMessage + tempChar;
        }
        
        if (s1.length() <= MAX)
        {
            txtEncOut.setText(encMessage);
        }
        
        else
        {
            txtEncOut.setText("This message is too long. Enter a message less than 31 characters long.");
        }
    }
    /*
        decAndRet
        
        This method receive a string value, declares the constant integer variables SHFT and MAX and assigns them 3 and 31 respectively, string variable decMessage, declares the char variable tempChar, declares the integer variable tempAcsii, uses a for loop statement, sets tempChar to the i character of the recieved variable, sets tempAcsii to the integer value of tempChar, 
        
        sets tempAcsii to 3 subtracted by itself, sets tempChar to the char value of tempAcsii, sets decMessage to tempChar added to itself, if statement used with the text box DecOut set to decMessage if it is true and else statement used if the if statement parameters are not met with the text box 
    
        displaying a message saying that the inputted value is not acceptable.
    
        Parameters: String
        
        Returns: void
    */
    public void decAndOut(String s1)
    {
        final int SHFT = 3;
        final int MAX = 31;
        String decMessage = "";
        char tempChar;
        int tempAcsii;
        
        for (int i = 0; i < s1.length(); i++)
        {
            tempChar = s1.charAt(i);
            tempAcsii = (int) tempChar;
            tempAcsii = tempAcsii - SHFT;
            tempChar = (char) tempAcsii;
            decMessage = decMessage + tempChar;
        }
        
        if (s1.length() <= MAX)
        {
            txtDecOut.setText(decMessage);
        }
        
        else
        {
            txtDecOut.setText("This message is too long. Enter a message less than 31 characters long.");
        }
    }

    /**
     * Creates new form EncryptDecrypt
     */
    public EncryptDecrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle2 = new javax.swing.JLabel();
        lblHeading2 = new javax.swing.JLabel();
        lblInst = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtEncIn = new javax.swing.JTextField();
        txtDecIn = new javax.swing.JTextField();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();
        txtEncOut = new javax.swing.JTextField();
        txtDecOut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(204, 0, 51));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("--TOP SECRET--");

        lblHeading2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeading2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading2.setText("--ENCRYPT/DECRYPT SOFTWARE--");

        lblInst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInst.setForeground(new java.awt.Color(204, 0, 51));
        lblInst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst.setText("Enter a decrypted message and it will be encrypted:");

        lblInst2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInst2.setForeground(new java.awt.Color(204, 0, 51));
        lblInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst2.setText("Enter an encrypted message and it will be decrypted:");

        lblHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(204, 0, 51));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("--ENCRYPT/DECRYPT SOFTWARE--");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("--TOP SECRET--");

        txtEncIn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEncIn.setForeground(new java.awt.Color(204, 0, 51));
        txtEncIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDecIn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDecIn.setForeground(new java.awt.Color(204, 0, 51));
        txtDecIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEncrypt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEncrypt.setForeground(new java.awt.Color(204, 0, 51));
        btnEncrypt.setText("ENCRYPT");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDecrypt.setForeground(new java.awt.Color(204, 0, 51));
        btnDecrypt.setText("DECRYPT");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        txtEncOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEncOut.setForeground(new java.awt.Color(204, 0, 51));
        txtEncOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEncOut.setText("*Encrypted message will be displayed here*");

        txtDecOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDecOut.setForeground(new java.awt.Color(204, 0, 51));
        txtDecOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDecOut.setText("* Decrypted message will be displayed here*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDecOut, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncOut, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDecIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(btnDecrypt)))
                    .addComponent(txtEncIn, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnEncrypt)))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTitle2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblHeading2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblInst))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblInst2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblHeading)
                .addGap(29, 29, 29)
                .addComponent(lblInst)
                .addGap(18, 18, 18)
                .addComponent(txtEncIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEncrypt)
                .addGap(18, 18, 18)
                .addComponent(txtEncOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInst2)
                .addGap(18, 18, 18)
                .addComponent(txtDecIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDecrypt)
                .addGap(18, 18, 18)
                .addComponent(txtDecOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblHeading2)
                .addGap(18, 18, 18)
                .addComponent(lblTitle2)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        String origMessage;         //string variable declared.
        
        origMessage = txtEncIn.getText();           //getting the input from the user and assigning it to a variable.
        
        encAndOut(origMessage);         //calling the encAndOut method and using the inputted value.
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        
        String encMessage = "";         //string variable declared.
        
        encMessage = txtDecIn.getText();           //getting the input from the user and assigning it to a variable.
        
        decAndOut(encMessage);         //calling the decAndOut method and using the inputted value.
    }//GEN-LAST:event_btnDecryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncryptDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncryptDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncryptDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncryptDecrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblInst;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTextField txtDecIn;
    private javax.swing.JTextField txtDecOut;
    private javax.swing.JTextField txtEncIn;
    private javax.swing.JTextField txtEncOut;
    // End of variables declaration//GEN-END:variables
}
